version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    restart: unless-stopped

  app1:
    image: litpon92/3th-chat-demo
    container_name: 3th-chat-app1
    restart: unless-stopped

  app2:
    image: litpon92/3th-chat-demo
    container_name: 3th-chat-app2
    restart: unless-stopped