name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Create application-prod.properties
      run: |
        cat << 'EOF' > src/main/resources/application-prod.properties
        ${{ secrets.PROD_PROPERTIES }}
        EOF
        
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build -t litpon92/3th-chat-demo:latest .
        docker push litpon92/3th-chat-demo:latest
        
    - name: Deploy to server
      run: |
        # Create SSH key file
        cat << 'EOF' > ssh_key
        ${{ secrets.INSTANCE_SECRET }}
        EOF
        chmod 600 ssh_key
        
        # Copy docker-compose files to server
        scp -i ssh_key -o StrictHostKeyChecking=no deploy/docker-compose.yml deploy/nginx.conf ec2-user@${{ secrets.INSTANCE_IP }}:~/
        
        # SSH to server and deploy
        ssh -i ssh_key -o StrictHostKeyChecking=no ec2-user@${{ secrets.INSTANCE_IP }} '
          sudo docker-compose down || true
          sudo docker-compose pull
          sudo docker-compose up -d
        '